import { z } from "zod";
import {
  ProjectType,
  Platform,
  AuthProvider,
  Theme,
  PrimaryColor,
  DesignStyle,
  AnimationLevel,
  ResponsiveMode,
  Frontend,
  Backend,
  Database,
  Styling,
  StateManagement,
  PaymentProvider,
  EmailProvider,
  NotificationType,
  FileUploadType,
  AdminLevel,
  AnalyticsProvider,
  Language,
  SecurityFeature,
  Deployment,
  TestType,
  DocType,
  GitFeature,
  OptionalFeature,
} from "@/types";

export const projectBlueprintSchema = z.object({
  id: z.string(),
  name: z.string().min(1, "Project name is required").max(100),
  projectType: z.enum([
    "todo",
    "inventory",
    "ecommerce",
    "chat",
    "blog",
    "portfolio",
    "crm",
    "lms",
    "hospital",
    "restaurant",
    "ai-saas",
    "social-media",
    "finance",
    "other",
  ]) as z.ZodType<ProjectType>,
  platform: z.enum(["website", "mobile", "desktop", "pwa", "website-mobile"]) as z.ZodType<Platform>,
  auth: z.enum(["none", "email", "google", "github", "multiple"]) as z.ZodType<AuthProvider>,
  theme: z.enum(["light", "dark", "light-dark", "system"]) as z.ZodType<Theme>,
  primaryColor: z.enum(["blue", "purple", "green", "orange", "red", "ai"]) as z.ZodType<PrimaryColor>,
  designStyle: z
    .enum(["apple", "material", "modern-saas", "glassmorphism", "minimal", "brutalist"]) as z.ZodType<DesignStyle>,
  animations: z.enum(["none", "minimal", "smooth", "fancy"]) as z.ZodType<AnimationLevel>,
  responsive: z.enum(["desktop", "mobile", "both"]) as z.ZodType<ResponsiveMode>,
  frontend: z.enum(["react", "nextjs", "vue", "svelte", "angular", "astro"]) as z.ZodType<Frontend>,
  backend: z.enum(["none", "express", "fastapi", "django", "laravel", "aspnet"]) as z.ZodType<Backend>,
  database: z
    .enum(["sqlite", "postgresql", "mysql", "mongodb", "firebase", "supabase"]) as z.ZodType<Database>,
  styling: z.enum(["tailwind", "shadcn", "mui", "bootstrap", "plaincss"]) as z.ZodType<Styling>,
  stateManagement: z
    .enum(["none", "zustand", "redux", "context", "pinia"]) as z.ZodType<StateManagement>,
  payments: z.enum(["none", "stripe", "paypal", "lemonsqueezy"]) as z.ZodType<PaymentProvider>,
  emailProvider: z.enum(["none", "resend", "sendgrid", "smtp"]) as z.ZodType<EmailProvider>,
  notifications: z.array(z.enum(["email", "push", "sms"]) as z.ZodType<NotificationType>),
  fileUpload: z.enum(["none", "images", "pdfs", "videos", "any"]) as z.ZodType<FileUploadType>,
  admin: z.enum(["none", "basic", "full"]) as z.ZodType<AdminLevel>,
  analytics: z.enum(["none", "google", "plausible", "umami"]) as z.ZodType<AnalyticsProvider>,
  languages: z.array(z.enum(["english", "french", "arabic", "spanish"]) as z.ZodType<Language>),
  security: z.array(z.enum(["rate-limiting", "email-verification", "captcha", "csrf", "2fa"]) as z.ZodType<SecurityFeature>),
  deployment: z.enum(["vercel", "netlify", "railway", "render", "docker", "vps"]) as z.ZodType<Deployment>,
  tests: z.array(z.enum(["unit", "integration", "e2e"]) as z.ZodType<TestType>),
  docs: z.array(z.enum(["readme", "api-docs", "architecture-diagram", "database-diagram", "user-guide"]) as z.ZodType<DocType>),
  gitFeatures: z.array(z.enum(["git", "github-actions", "cicd", "issue-templates"]) as z.ZodType<GitFeature>),
  optionalFeatures: z.array(z.enum([
    "search",
    "filters",
    "tags",
    "export-csv",
    "export-pdf",
    "drag-drop",
    "offline",
    "autosave",
    "undo-redo",
    "infinite-scroll",
    "pagination",
    "calendar",
    "kanban",
    "charts",
    "markdown",
    "rich-text",
    "comments",
    "likes",
    "bookmarks",
    "profiles",
    "qr-codes",
    "share-links",
    "audit-logs",
    "version-history",
    "websockets",
    "realtime",
    "presence",
    "api",
    "webhooks",
  ]) as z.ZodType<OptionalFeature>),
  currentStep: z.number().min(1).max(26),
  lastUpdated: z.number(),
});

export const aiConfigSchema = z.object({
  apiKey: z.string().min(1, "API key is required"),
  model: z.string().min(1),
  temperature: z.number().min(0).max(2).default(0.7),
  maxTokens: z.number().min(1).max(4096).default(4096),
  connected: z.boolean().default(false),
});